# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SEED": "01_Representation.ipynb",
         "get_example_dataset": "00_core.ipynb",
         "get_mnist_dataset": "00_core.ipynb",
         "Tree": "01_Representation.ipynb",
         "SymbolicInstance": "02_SymbolicInstance.ipynb",
         "SymbolicPredictionSolver": "02_SymbolicInstance.ipynb",
         "CoordinateDescent": "02_SymbolicInstance.ipynb"}

modules = ["core.py",
           "tree.py",
           "symbolic_prediction.py"]

doc_url = "https://numb3r33.github.io/tree_evasion/"

git_url = "https://github.com/numb3r33/tree_evasion/tree/master/"

def custom_doc_links(name): return None
