'''
Author: your name
Date: 2021-04-19 09:54:08
LastEditTime: 2021-05-27 17:34:12
LastEditors: Please set LastEditors
Description: In User Settings Edit
FilePath: /Cyber-Security-ML-Toolbox/tree_evasion/core.py
'''
# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['SEED', 'get_example_dataset', 'get_mnist_dataset', 'get_example_dataset', 'get_mnist_dataset']

# Cell
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split as tts
from sklearn.datasets import fetch_openml

SEED = 41
np.random.seed(SEED)

# Cell
def get_example_dataset(SEED):
    X, y = make_classification(n_samples = 100, n_features=5, random_state=SEED)
    Xtr, Xte, ytr, yte = tts(X, y, test_size=0.2, random_state=SEED)

    return Xtr, Xte, ytr, yte

# Cell
def get_mnist_dataset(SEED):

    X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
    X = X / 255.

    ridx = np.random.permutation(len(X))
    X_random = X[ridx]
    y_random = y[ridx]

    idxs = np.where((y_random == '2') | (y_random == '6'))[0]
    Xs, ys = X_random[idxs], y_random[idxs]

    Xtr, Xte, ytr, yte = tts(Xs, ys, test_size=0.2, random_state=SEED)
    Xtr, Xva, ytr, yva = tts(Xtr, ytr, test_size=0.2, random_state=SEED)

    return (Xtr, Xva, Xte, ytr, yva, yte)